; interrupcion TMR0 

	LIST	P=18F4550
	#INCLUDE	<P18F4550.INC>
	
	CONFIG	FOSC=INTOSCIO_EC
	CONFIG	BOR=OFF	
	CONFIG	CP0=OFF	
	CONFIG	CP1=OFF	
	CONFIG	CPB=OFF	
	CONFIG	DEBUG=OFF	
	CONFIG	LVP=OFF	
	CONFIG	MCLRE=OFF	
	CONFIG	PBADEN=OFF
	CONFIG	PWRT=ON
	CONFIG	XINST=OFF	
	CONFIG	WDT=OFF	

	CBLOCK	0X20
	CT0
	TEMP
	BANDERA
	ENDC

	ORG		0X0000
	GOTO	INICIO

	ORG		0X0008
	GOTO	ISR_T0

CPORTS
	MOVLW	0FH
	MOVWF	ADCON1
	MOVLW	07H
	MOVWF	CMCON
	MOVLW	62H
	MOVWF	OSCCON
	CLRF	TRISD
	CLRF	LATD
	RETURN

CONFT0			; configuracion del tmr0
	MOVLW	47H
	MOVWF	T0CON
	BCF		RCON,IPEN
	BSF		INTCON,TMR0IE
	BSF		INTCON,TMR0IP
	BSF		INTCON,PEIE
	MOVLW	.61			; dato sacado de la formula 
	MOVWF	TMR0L
	MOVLW	.40			; multiplicacion por 40 decimal apra acompletar 1 seg 
	MOVWF	CT0
	BCF		INTCON,TMR0IF ; limpiamos banderas
	RETURN

HOLA
	RLNCF	TEMP,W
	ADDWF	PCL,F
	DT		B'00110110',B'00111111',B'00111000',B'01110111'
BYE
	RLNCF	TEMP,W
	ADDWF	PCL,F
	DT		B'01111100',B'01100110',B'01111001'

ISR_T0
		BTFSS	INTCON,TMR0IF
		BRA		FIN
		DECFSZ	CT0,F
		BRA		FIN2
		BSF		BANDERA,0
		MOVLW	.40
		MOVWF	CT0
		MOVLW	.61
FIN2	MOVWF	TMR0L
		BCF		INTCON,TMR0IF
FIN		RETFIE

INICIO
		RCALL	CPORTS
		RCALL	CONFT0
		CLRF	TEMP
		BSF		T0CON,TMR0ON
		BSF		INTCON,GIE
AQUI	CLRF	TEMP
		BTFSS	BANDERA,0
		BRA		ADIOS
OTRO	BCF		BANDERA,0
		RCALL	HOLA
		MOVWF	LATD
		INCF	TEMP,F
		MOVLW	.4
		SUBWF	TEMP,W
		BZ		AQUI	
		BRA		OTRO
ADIOS	RCALL	BYE
		MOVWF	LATD
		INCF	TEMP,F
		MOVLW	.3
		SUBWF	TEMP,W
		BZ		AQUI	
		BRA		ADIOS
		END

	
	