;PROGRAMA QUE UTILIZA EL DIRECCIONAMIENTO INDIRECTO
;PARA GRABAR EL NUMERO 8 EN UNA TABLA Y DESPUES BORRAR LA TABLA


	LIST	P=18F4550
	#INCLUDE	<P18F4550.INC>
	
	CONFIG	FOSC	=	INTOSCIO_EC
	CONFIG	LVP		=	OFF
	CONFIG	MCLRE	=	OFF
	CONFIG	DEBUG	=	OFF
	CONFIG	XINST	=	OFF
	CONFIG	PBADEN	=	OFF
	CONFIG	CP0		=	OFF
	CONFIG	CP1		=	OFF
	CONFIG	CPB		=	OFF
	CONFIG	BOR		=	OFF
	CONFIG 	WDT		=	OFF
	CONFIG	PWRT	=	ON
	
	CBLOCK	20H
	TABLA:9
	ENDC
	
	ORG	0X0000
	GOTO	INICIO
	
	ORG	0X0018
	GOTO	INICIO
	
	CPORTS
		MOVLW	0X0F
		MOVWF	ADCON1
		MOVLW	0X07
		MOVWF	CMCON
		MOVLW	0X62
		MOVWF	OSCCON
		RETURN
		
INICIO	
		RCALL	CPORTS
		MOVLW	0X20
		MOVWF	FSR0L	;APUNTA A DIRECCION 20
OTRO	MOVLW	0X08
		MOVWF	INDF0	;GUARDA 8 EN LA DIRECCION APUNTADA
		INCF	FSR0L,F	;INCREMENTO APUNTADOR
		MOVF	FSR0L,W
		XORLW	0x29	;si fsr0 llega a 29 ya termino 
		BTFSS	STATUS,Z	;Z=1 SALTA PORQUE W FUE 29
		BRA		OTRO
		
		MOVLW	0X20
		MOVWF	FSR0L
OTRO2	CLRF	INDF0
		INCF	FSR0L,F
		MOVF	FSR0L,W
		XORLW	0X29
		BTFSS	STATUS,Z
		BRA		OTRO2
	END
	
	
	
	